<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-21T12:55:29+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'locale' => 'de_DE',
    'site' => 'EZ_AKA',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1474455143,
        'latest_version' => '5.7.5.9',
    ),
);
